#pragma once

#include <BWAPI.h>

class UnitType
{
public:
    static UnitType* getUnitType(BWAPI::UnitType unitType);
    static void emptyCache();

    bool operator==(const UnitType& rhs) const;

    bool isWorker() const;
    bool isMineralField() const;

private:
    static std::map<int, UnitType*> unitTypeMap;

	UnitType(BWAPI::UnitType unitType);

    BWAPI::UnitType unitType;

public:
    static const UnitType Terran_Marine;
    static const UnitType Hero_Jim_Raynor_Marine;
    static const UnitType Terran_Ghost;
    static const UnitType Hero_Sarah_Kerrigan;
    static const UnitType Hero_Samir_Duran;
    static const UnitType Hero_Infested_Duran;
    static const UnitType Hero_Alexei_Stukov;
    static const UnitType Terran_Vulture;
    static const UnitType Hero_Jim_Raynor_Vulture;
    static const UnitType Terran_Goliath;
    static const UnitType Hero_Alan_Schezar;
    static const UnitType Terran_Siege_Tank_Tank_Mode;
    static const UnitType Hero_Edmund_Duke_Tank_Mode;
    static const UnitType Terran_SCV;
    static const UnitType Terran_Wraith;
    static const UnitType Hero_Tom_Kazansky;
    static const UnitType Terran_Science_Vessel;
    static const UnitType Hero_Magellan;
    static const UnitType Terran_Dropship;
    static const UnitType Terran_Battlecruiser;
    static const UnitType Hero_Arcturus_Mengsk;
    static const UnitType Hero_Hyperion;
    static const UnitType Hero_Norad_II;
    static const UnitType Hero_Gerard_DuGalle;
    static const UnitType Terran_Vulture_Spider_Mine;
    static const UnitType Terran_Nuclear_Missile;
    static const UnitType Terran_Siege_Tank_Siege_Mode;
    static const UnitType Hero_Edmund_Duke_Siege_Mode;
    static const UnitType Terran_Firebat;
    static const UnitType Hero_Gui_Montag;
    static const UnitType Spell_Scanner_Sweep;
    static const UnitType Terran_Medic;
    static const UnitType Terran_Civilian;
    static const UnitType Zerg_Larva;
    static const UnitType Zerg_Egg;
    static const UnitType Zerg_Zergling;
    static const UnitType Hero_Devouring_One;
    static const UnitType Hero_Infested_Kerrigan;
    static const UnitType Zerg_Hydralisk;
    static const UnitType Hero_Hunter_Killer;
    static const UnitType Zerg_Ultralisk;
    static const UnitType Hero_Torrasque;
    static const UnitType Zerg_Broodling;
    static const UnitType Zerg_Drone;
    static const UnitType Zerg_Overlord;
    static const UnitType Hero_Yggdrasill;
    static const UnitType Zerg_Mutalisk;
    static const UnitType Hero_Kukulza_Mutalisk;
    static const UnitType Zerg_Guardian;
    static const UnitType Hero_Kukulza_Guardian;
    static const UnitType Zerg_Queen;
    static const UnitType Hero_Matriarch;
    static const UnitType Zerg_Defiler;
    static const UnitType Hero_Unclean_One;
    static const UnitType Zerg_Scourge;
    static const UnitType Zerg_Infested_Terran;
    static const UnitType Terran_Valkyrie;
    static const UnitType Zerg_Cocoon;
    static const UnitType Protoss_Corsair;
    static const UnitType Hero_Raszagal;
    static const UnitType Protoss_Dark_Templar;
    static const UnitType Hero_Dark_Templar;
    static const UnitType Hero_Zeratul;
    static const UnitType Zerg_Devourer;
    static const UnitType Protoss_Dark_Archon;
    static const UnitType Protoss_Probe;
    static const UnitType Protoss_Zealot;
    static const UnitType Hero_Fenix_Zealot;
    static const UnitType Protoss_Dragoon;
    static const UnitType Hero_Fenix_Dragoon;
    static const UnitType Protoss_High_Templar;
    static const UnitType Hero_Tassadar;
    static const UnitType Hero_Aldaris;
    static const UnitType Protoss_Archon;
    static const UnitType Hero_Tassadar_Zeratul_Archon;
    static const UnitType Protoss_Shuttle;
    static const UnitType Protoss_Scout;
    static const UnitType Hero_Mojo;
    static const UnitType Hero_Artanis;
    static const UnitType Protoss_Arbiter;
    static const UnitType Hero_Danimoth;
    static const UnitType Protoss_Carrier;
    static const UnitType Hero_Gantrithor;
    static const UnitType Protoss_Interceptor;
    static const UnitType Protoss_Reaver;
    static const UnitType Hero_Warbringer;
    static const UnitType Protoss_Observer;
    static const UnitType Protoss_Scarab;
    static const UnitType Critter_Rhynadon;
    static const UnitType Critter_Bengalaas;
    static const UnitType Special_Cargo_Ship;
    static const UnitType Special_Mercenary_Gunship;
    static const UnitType Critter_Scantid;
    static const UnitType Critter_Kakaru;
    static const UnitType Critter_Ragnasaur;
    static const UnitType Critter_Ursadon;
    static const UnitType Zerg_Lurker_Egg;
    static const UnitType Zerg_Lurker;
    static const UnitType Spell_Disruption_Web;
    static const UnitType Terran_Command_Center;
    static const UnitType Terran_Comsat_Station;
    static const UnitType Terran_Nuclear_Silo;
    static const UnitType Terran_Supply_Depot;
    static const UnitType Terran_Refinery;
    static const UnitType Terran_Barracks;
    static const UnitType Terran_Academy;
    static const UnitType Terran_Factory;
    static const UnitType Terran_Starport;
    static const UnitType Terran_Control_Tower;
    static const UnitType Terran_Science_Facility;
    static const UnitType Terran_Covert_Ops;
    static const UnitType Terran_Physics_Lab;
    static const UnitType Terran_Machine_Shop;
    static const UnitType Terran_Engineering_Bay;
    static const UnitType Terran_Armory;
    static const UnitType Terran_Missile_Turret;
    static const UnitType Terran_Bunker;
    static const UnitType Special_Crashed_Norad_II;
    static const UnitType Special_Ion_Cannon;
    static const UnitType Zerg_Infested_Command_Center;
    static const UnitType Zerg_Hatchery;
    static const UnitType Zerg_Lair;
    static const UnitType Zerg_Hive;
    static const UnitType Zerg_Nydus_Canal;
    static const UnitType Zerg_Hydralisk_Den;
    static const UnitType Zerg_Defiler_Mound;
    static const UnitType Zerg_Greater_Spire;
    static const UnitType Zerg_Queens_Nest;
    static const UnitType Zerg_Evolution_Chamber;
    static const UnitType Zerg_Ultralisk_Cavern;
    static const UnitType Zerg_Spire;
    static const UnitType Zerg_Spawning_Pool;
    static const UnitType Zerg_Creep_Colony;
    static const UnitType Zerg_Spore_Colony;
    static const UnitType Zerg_Sunken_Colony;
    static const UnitType Special_Overmind_With_Shell;
    static const UnitType Special_Overmind;
    static const UnitType Zerg_Extractor;
    static const UnitType Special_Mature_Chrysalis;
    static const UnitType Special_Cerebrate;
    static const UnitType Special_Cerebrate_Daggoth;
    static const UnitType Protoss_Nexus;
    static const UnitType Protoss_Robotics_Facility;
    static const UnitType Protoss_Pylon;
    static const UnitType Protoss_Assimilator;
    static const UnitType Protoss_Observatory;
    static const UnitType Protoss_Gateway;
    static const UnitType Protoss_Photon_Cannon;
    static const UnitType Protoss_Citadel_of_Adun;
    static const UnitType Protoss_Cybernetics_Core;
    static const UnitType Protoss_Templar_Archives;
    static const UnitType Protoss_Forge;
    static const UnitType Protoss_Stargate;
    static const UnitType Special_Stasis_Cell_Prison;
    static const UnitType Protoss_Fleet_Beacon;
    static const UnitType Protoss_Arbiter_Tribunal;
    static const UnitType Protoss_Robotics_Support_Bay;
    static const UnitType Protoss_Shield_Battery;
    static const UnitType Special_Khaydarin_Crystal_Form;
    static const UnitType Special_Protoss_Temple;
    static const UnitType Special_XelNaga_Temple;
    static const UnitType Resource_Mineral_Field;
    static const UnitType Resource_Mineral_Field_Type_2;
    static const UnitType Resource_Mineral_Field_Type_3;
    static const UnitType Special_Independant_Starport;
    static const UnitType Resource_Vespene_Geyser;
    static const UnitType Special_Warp_Gate;
    static const UnitType Special_Psi_Disrupter;
    static const UnitType Special_Power_Generator;
    static const UnitType Special_Overmind_Cocoon;
    static const UnitType Special_Zerg_Beacon;
    static const UnitType Special_Terran_Beacon;
    static const UnitType Special_Protoss_Beacon;
    static const UnitType Special_Zerg_Flag_Beacon;
    static const UnitType Special_Terran_Flag_Beacon;
    static const UnitType Special_Protoss_Flag_Beacon;
    static const UnitType Spell_Dark_Swarm;
    static const UnitType Powerup_Uraj_Crystal;
    static const UnitType Powerup_Khalis_Crystal;
    static const UnitType Powerup_Flag;
    static const UnitType Powerup_Young_Chrysalis;
    static const UnitType Powerup_Psi_Emitter;
    static const UnitType Powerup_Data_Disk;
    static const UnitType Powerup_Khaydarin_Crystal;
    static const UnitType Powerup_Mineral_Cluster_Type_1;
    static const UnitType Powerup_Mineral_Cluster_Type_2;
    static const UnitType Powerup_Protoss_Gas_Orb_Type_1;
    static const UnitType Powerup_Protoss_Gas_Orb_Type_2;
    static const UnitType Powerup_Zerg_Gas_Sac_Type_1;
    static const UnitType Powerup_Zerg_Gas_Sac_Type_2;
    static const UnitType Powerup_Terran_Gas_Tank_Type_1;
    static const UnitType Powerup_Terran_Gas_Tank_Type_2;
    static const UnitType Special_Map_Revealer;
    static const UnitType Special_Floor_Missile_Trap;
    static const UnitType Special_Floor_Hatch;
    static const UnitType Special_Upper_Level_Door;
    static const UnitType Special_Right_Upper_Level_Door;
    static const UnitType Special_Pit_Door;
    static const UnitType Special_Right_Pit_Door;
    static const UnitType Special_Floor_Gun_Trap;
    static const UnitType Special_Wall_Missile_Trap;
    static const UnitType Special_Wall_Flame_Trap;
    static const UnitType Special_Right_Wall_Missile_Trap;
    static const UnitType Special_Right_Wall_Flame_Trap;
    static const UnitType Special_Start_Location;

    static const UnitType None;
    static const UnitType AllUnits;
    static const UnitType Men;
    static const UnitType Buildings;
    static const UnitType Factories;
    static const UnitType Unknown;
};